metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']
    remote_write:
      - url: ${GRAFANA_WRITE_URL}
        basic_auth:
          username: ${GRAFANA_USERNAME}
          password: ${GRAFANA_PASSWORD}
